### ISSUE TITLE
Link to the programmer policies is broken.

### ISSUE THREAD

**Issue by Tanvish** [umts/dev-training#30]
Read the transportation programmer policies Tanvish/dev-training-priv#30 has a link that does not lead you to the right directory of the files that are needed to be looked at in the issue.

**Comment by werebus** [comment]
To be clear, we're talking about this qualification?

https://github.com/umts/dev-training/blob/b25c27c26333278f64ee820fa49686ae624b3619/config/qualifications.yml#L24

Link looks right to me. Perhaps this is actually a problem with your Box permissions?

**Comment by Anbranin** [comment]
@sherson, Matt and I can't add people to groups OR make a new group. Perhaps a group called "programmer trainees" or something?

**Comment by werebus** [comment]
This is all set. @sherson corrected the Box issues this morning.

**Comment by sherson** [comment]
@Anbranin commented:

> Matt and I can't add people to groups OR make a new group

None of us have the ability to make a new group, but you, @werebus, @umayavuz, and I can now manage membership for these groups (created for us by UMIT):

* Transportation Programmer Trainees
* Transportation Programmers

**Comment by Anbranin** [comment]
OK kewl thanks boss
