### ISSUE TITLE
Github setup tweeks

### ISSUE THREAD

**Issue by werebus** [umts/dev-training#34]
Some things that were missed at least by some in setting up GitHub

*  2FA
*  SSH Key
*  Our (slight) preference for cloning over SSH rather than HTTPS

**Comment by Anbranin** [comment]
So I need to change the issue to explain how to set each of these up/ what they are, basically?

**Comment by werebus** [comment]
Well, we have [this one](https://github.com/umts/dev-training/blob/37eaff8b4800e39e47777ecbedbf42c36fce77f4/config/qualifications.yml#L6), but I notice we _don't_ have "sign up for GitHub". I would recommend adding:

*  Sign up for GitHub, tell us your username, don't forget 2FA
*  Set up an SSH keypair (link to instructions) with GitHub. Use the SSH URL for cloning from now on.

**Comment by Anbranin** [comment]
Did this, forgot to close issue.
