### ISSUE TITLE
Bootstrap script asks for password for UMTS, tries to create a repository in UMTS

### ISSUE THREAD

**Issue by Anbranin** [umts/dev-training#62]
When the client asks for a password, it's the password for the `umts` user on Github. We got past this by editing the client.rb file. However, after that, we realized it was trying to add issues to this repository--Ben didn't have permissions, I did, which is why the script "worked" for me.

So we've manually created all the dev-training forks and added issues by copying and pasting. The whole API is changing in September before we have to train anyone else anyways.

**Comment by werebus** [comment]
![2020-05-14_14-55](https://user-images.githubusercontent.com/240275/81973988-ed0e8f00-95f2-11ea-91d7-cb92ad1e1825.png)

**Comment by Anbranin** [comment]
Words cannot convey how stupid I feel at this moment.

**Comment by Anbranin** [comment]
We were doing everything right but, crucially, not forking first. I have no idea why I was ignoring that part of the README.
